// HadeelBeauty storefront config — Algérie
window.HADEELBEAUTY_CONFIG = {
  API_BASE: "", // same-origin via nginx /api/ proxy on hadeelbeauty.store
  STORE_URL: "https://hadeelbeauty.store",

  META_PIXEL_ID: "1027331430352258",
  TIKTOK_PIXEL_ID: "",
  SNAPCHAT_PIXEL_ID: "",

  PRODUCT_META: {
    "scar-gel-tcm": {
      emoji: "✨",
      category: "ندبات · حب الشباب",
      gradient: "linear-gradient(135deg, #fff8e1, #d4a574)",
      image: "assets/products/scar-gel/hero-product.png?v=1",
    },
    "arencia-nad-booster": {
      emoji: "💜",
      category: "تجديد · بشرة باهتة",
      gradient: "linear-gradient(135deg, #f4f1fa, #c5b8e0)",
      image: "assets/products/arencia-nad-booster/hero-product.png?v=1",
    },
    "arencia-eraser-glycolic": {
      emoji: "🩶",
      category: "تقشير · مسام",
      gradient: "linear-gradient(135deg, #f6f4f1, #c8c4be)",
      image: "assets/products/arencia-eraser-glycolic/hero-product.png?v=1",
    },
    "arencia-txa-booster": {
      emoji: "🪸",
      category: "بقع · توحيد اللون",
      gradient: "linear-gradient(135deg, #fdf4f0, #e8a090)",
      image: "assets/products/arencia-txa-booster/hero-product.png?v=1",
    },
    "arencia-pdrn-booster": {
      emoji: "🌸",
      category: "تهدئة · تجديد",
      gradient: "linear-gradient(135deg, #fdf4f6, #d4a0b0)",
      image: "assets/products/arencia-pdrn-booster/hero-product.png?v=1",
    },
    "arencia-retinal-booster": {
      emoji: "🌙",
      category: "شد · ليلي",
      gradient: "linear-gradient(135deg, #fffbe8, #f0d24a)",
      image: "assets/products/arencia-retinal-booster/hero-product.png?v=1",
    },
    "arencia-vitamin-c-booster": {
      emoji: "🍋",
      category: "إشراق · تفتيح",
      gradient: "linear-gradient(135deg, #f7fbe8, #c5d45a)",
      image: "assets/products/arencia-vitamin-c-booster/hero-product.png?v=1",
    },
    "niacinamide-serum": {
      emoji: "💧",
      category: "مسام · بشرة دهنية",
      gradient: "linear-gradient(135deg, #fdf6f3, #d1717f)",
      image: "assets/assets/products/niacinamide-serum/hero-product.png",
    },
    "vitamin-c-serum": {
      emoji: "☀️",
      category: "تفتيح · إشراق",
      gradient: "linear-gradient(135deg, #fffdf0, #ffaa00)",
      image: "assets/assets/products/vitamin-c-serum/hero-product.png",
    },
    "arbutin-cream": {
      emoji: "🌸",
      category: "تفتيح · بقع داكنة",
      gradient: "linear-gradient(135deg, #fdf8f5, #e8aabb)",
      image: "assets/assets/products/arbutin-cream/hero-product.png",
    },
    "spf50-sunscreen": {
      emoji: "🌞",
      category: "حماية · واقي شمس",
      gradient: "linear-gradient(135deg, #fff9f0, #ffd966)",
      image: "assets/assets/products/spf50-sunscreen/hero-product.png",
    },
    "ceramide-cream": {
      emoji: "🛡️",
      category: "ترطيب · بشرة جافة",
      gradient: "linear-gradient(135deg, #f0f7f6, #7eb8b0)",
      image: "assets/assets/products/ceramide-cream/hero-product.png",
    },
    "rosemary-hair-oil": {
      emoji: "🌿",
      category: "شعر · تساقط",
      gradient: "linear-gradient(135deg, #f0f7ee, #40916c)",
      image: "assets/assets/products/rosemary-hair-oil/hero-product.png",
    },
    "retinol-serum": {
      emoji: "🌙",
      category: "مضاد شيخوخة · ليلي",
      gradient: "linear-gradient(135deg, #1a1a2e, #7b2d8b)",
      image: "assets/assets/products/retinol-serum/hero-product.png",
    },
  },

  PRODUCT_PROFILES: {
    "scar-gel-tcm": {
      badge: "✨ الأكثر طلباً",
      weight: "30 جرام · COD",
      pills: ["💵 الدفع عند الاستلام", "📦 افحصي المنتج قبل الدفع", "🚚 توصيل 58 ولاية", "🌿 تركيبة TCM لطيفة"],
      highlights: [
        { icon: "🛡️", title: "حماية", text: "يساعد على تقليل ظهور الندبات بعد الجروح والعمليات" },
        { icon: "✨", title: "توحيد اللون", text: "نياسيناميد وأربوتين لدعم مظهر أكثر توازناً" },
        { icon: "💧", title: "ترطيب", text: "هيالورونات الصوديوم لترطيب دون دهون" },
        { icon: "🌿", title: "لطيف", text: "قوام شفاف سريع الامتصاص — لجميع أنواع البشرة" },
      ],
      specs: [
        ["الوزن الصافي", "30 جرام"],
        ["النوع", "جل شفاف"],
        ["الاستخدام", "مساءً — يومي"],
        ["أنواع البشرة", "جميع الأنواع"],
        ["المكونات البارزة", "سنتيلا آسياتيكا، نياسيناميد، أربوتين"],
        ["التوصيل", "58 ولاية — الدفع عند الاستلام"],
      ],
      gallery: true,
    },
    "arencia-nad-booster": {
      badge: "💜 NAD+ Booster",
      weight: "30 مل · COD",
      pills: ["💵 الدفع عند الاستلام", "📦 افحصي قبل الدفع", "🚚 توصيل 58 ولاية", "💜 NAD+ 5%"],
      highlights: [
        { icon: "💜", title: "NAD+ 5%", text: "يدعم مظهر بشرة أكثر حيوية ونشاطاً — خاصة البشرة الباهتة والتعبة" },
        { icon: "🌿", title: "ريسفيراترول", text: "مضاد أكسدة نباتي يساعد على حماية مظهر البشرة من الإجهاد" },
        { icon: "✨", title: "ببتيدات", text: "تدعم مظهراً أكثر نعومة وثباتاً مع الاستعمال المنتظم" },
        { icon: "👁️", title: "وجه ومحيط العين", text: "مرطب خفيف للوجه ومحيط العين — صباحاً ومساءً" },
      ],
      specs: [
        ["الحجم", "30 مل"],
        ["المكونات البارزة", "NAD+ 5%، ريسفيراترول، ببتيدات"],
        ["الاستخدام", "صباحاً ومساءً بعد التنظيف"],
        ["الأنسب لـ", "البشرة الباهتة والتعبة"],
        ["التوصيل", "58 ولاية — الدفع عند الاستلام"],
      ],
      gallery: false,
    },
    "arencia-eraser-glycolic": {
      badge: "🩶 Eraser Shot",
      weight: "30 مل · COD",
      pills: ["💵 الدفع عند الاستلام", "📦 افحصي قبل الدفع", "🚚 توصيل 58 ولاية", "🩶 تقشير لطيف"],
      highlights: [
        { icon: "🩶", title: "حمض الجليكوليك (AHA)", text: "يقشّر الطبقة السطحية بلطف وينعّم ملمس البشرة الخشن" },
        { icon: "🔬", title: "BHA", text: "يساعد على تخفيف مظهر الاحتقان والرؤوس السوداء داخل المسام" },
        { icon: "🌿", title: "تهدئة", text: "تركيبة مخصّصة لتنعيم الملمس دون وعد بإزالة حب الشباب فوراً" },
        { icon: "🌙", title: "استعمال ليلي", text: "ابدئي كل ليلة أو ليلتين، ودائماً واقي شمس في النهار" },
      ],
      specs: [
        ["الحجم", "30 مل"],
        ["المكونات البارزة", "حمض الجليكوليك، BHA"],
        ["الاستخدام", "ليلاً — ابدئي تدريجياً"],
        ["الأنسب لـ", "الملمس الخشن والاحتقان"],
        ["تنبيه", "لا تخلطيه مع ريتينال أو فيتامين سي في نفس الروتين"],
        ["التوصيل", "58 ولاية — الدفع عند الاستلام"],
      ],
      gallery: false,
    },
    "arencia-txa-booster": {
      badge: "🪸 TXA Booster",
      weight: "30 مل · COD",
      pills: ["💵 الدفع عند الاستلام", "📦 افحصي قبل الدفع", "🚚 توصيل 58 ولاية", "🪸 TXA 5%"],
      highlights: [
        { icon: "🪸", title: "TXA 5%", text: "يساعد على تلطيف مظهر البقع الداكنة وتفاوت اللون تدريجياً" },
        { icon: "✨", title: "ببتيدات", text: "تدعم مظهراً أكثر نعومة ووضوحاً مع الاستعمال المنتظم" },
        { icon: "🌸", title: "توحيد اللون", text: "للتصبغات وآثار البقع — بلا ادّعاء محو فوري" },
        { icon: "👁️", title: "وجه ومحيط العين", text: "خفيف على البشرة — صباحاً ومساءً مع واقي شمس" },
      ],
      specs: [
        ["الحجم", "30 مل"],
        ["المكونات البارزة", "TXA 5%، ببتيدات"],
        ["الاستخدام", "صباحاً ومساءً — مع واقي شمس نهاراً"],
        ["الأنسب لـ", "البقع الداكنة وتفاوت اللون"],
        ["التوصيل", "58 ولاية — الدفع عند الاستلام"],
      ],
      gallery: false,
    },
    "arencia-pdrn-booster": {
      badge: "🌸 PDRN Booster",
      weight: "30 مل · COD",
      pills: ["💵 الدفع عند الاستلام", "📦 افحصي قبل الدفع", "🚚 توصيل 58 ولاية", "🌸 مناسب للحساسة"],
      highlights: [
        { icon: "🌸", title: "Rosy-PDRN 5%", text: "يدعم مظهر بشرة مرتاحة وأكثر تماسكًا بعد الإجهاد أو الاحمرار" },
        { icon: "💧", title: "ببتيدات", text: "ترطيب ودعْم لمظهر أكثر نعومة وثباتاً" },
        { icon: "🌿", title: "تهدئة", text: "مناسب للبشرة الحساسة والمعرّضة للاحمرار" },
        { icon: "👁️", title: "وجه ومحيط العين", text: "مرطب يومي لطيف — صباحاً ومساءً" },
      ],
      specs: [
        ["الحجم", "30 مل"],
        ["المكونات البارزة", "Rosy-PDRN 5%، ببتيدات"],
        ["الاستخدام", "صباحاً ومساءً بعد التنظيف"],
        ["الأنسب لـ", "البشرة الحساسة والاحمرار"],
        ["التوصيل", "58 ولاية — الدفع عند الاستلام"],
      ],
      gallery: false,
    },
    "arencia-retinal-booster": {
      badge: "🌙 Retinal Booster",
      weight: "30 مل · COD",
      pills: ["💵 الدفع عند الاستلام", "📦 افحصي قبل الدفع", "🚚 توصيل 58 ولاية", "🌙 استعمال ليلي"],
      highlights: [
        { icon: "🌙", title: "ريتينال 2%", text: "مشتق فيتامين A يدعم مظهر أكثر نعومة وثباتاً مع الروتين الليلي" },
        { icon: "☕", title: "كافيين", text: "يساعد على تخفيف مظهر الانتفاخ والتعب حول العين" },
        { icon: "✨", title: "شدّ لطيف", text: "ليس وصفة طبية — يدعم مرونة المظهر تدريجياً" },
        { icon: "🛡️", title: "ابدئي ببطء", text: "ليلة بعد ليلة حتى تعتاد البشرة — وواقي شمس في الصباح" },
      ],
      specs: [
        ["الحجم", "30 مل"],
        ["المكونات البارزة", "ريتينال (مركب 2%)، كافيين"],
        ["الاستخدام", "ليلاً فقط — ابدئي كل ليلتين"],
        ["الأنسب لـ", "فقدان الثبات وعلامات التعب"],
        ["تنبيه", "لا تخلطيه مع فيتامين سي أو أحماض التقشير في نفس الروتين"],
        ["التوصيل", "58 ولاية — الدفع عند الاستلام"],
      ],
      gallery: false,
    },
    "arencia-vitamin-c-booster": {
      badge: "🍋 Vitamin C Booster",
      weight: "30 مل · COD",
      pills: ["💵 الدفع عند الاستلام", "📦 افحصي قبل الدفع", "🚚 توصيل 58 ولاية", "🍋 فيتامين سي 5%"],
      highlights: [
        { icon: "🍋", title: "فيتامين سي 5%", text: "يساعد على إشراق البشرة وتلطيف مظهر البهتان" },
        { icon: "✨", title: "جلوتاثيون", text: "مضاد أكسدة يدعم وضوح اللون ومظهراً أكثر إشراقاً" },
        { icon: "☀️", title: "روتين الصباح", text: "يُفضّل صباحاً ثم واقي شمس — لا تخلطيه مع ريتينال" },
        { icon: "👁️", title: "وجه ومحيط العين", text: "مرطب خفيف للوجه ومحيط العين" },
      ],
      specs: [
        ["الحجم", "30 مل"],
        ["المكونات البارزة", "فيتامين سي 5%، جلوتاثيون"],
        ["الاستخدام", "صباحاً قبل واقي الشمس"],
        ["الأنسب لـ", "البشرة الباهتة وقلة الإشراق"],
        ["تنبيه", "لا تخلطيه مع ريتينال أو أحماض التقشير في نفس الروتين"],
        ["التوصيل", "58 ولاية — الدفع عند الاستلام"],
      ],
      gallery: false,
    },
    "niacinamide-serum": {
      badge: "🔥 ترند الجزائر",
      weight: "30 مل · COD",
      pills: ["💵 الدفع عند الاستلام", "🚚 توصيل 58 ولاية", "💧 نياسيناميد 10%", "🌿 مناسب للبشرة الدهنية"],
      highlights: [
        { icon: "🔬", title: "نياسيناميد 10%", text: "يُضيّق المسام ويُقلّل الإفرازات الزيتية بشكل ملحوظ" },
        { icon: "✨", title: "توحيد اللون", text: "يُخفّف البقع الداكنة وآثار حب الشباب تدريجياً" },
        { icon: "🛡️", title: "زنك 1%", text: "يُهدّئ الالتهابات ويُقلّل احمرار البشرة" },
        { icon: "💧", title: "قوام خفيف", text: "سريع الامتصاص — لا يُثقّل البشرة ولا يُسبّب الدهون" },
      ],
      specs: [
        ["الحجم", "30 مل"],
        ["التركيز", "نياسيناميد 10% + زنك 1%"],
        ["الاستخدام", "صباحاً ومساءً بعد التنظيف"],
        ["أنواع البشرة", "دهنية، مختلطة، شبابية"],
        ["التوصيل", "58 ولاية — الدفع عند الاستلام"],
      ],
      gallery: false,
    },
    "vitamin-c-serum": {
      badge: "☀️ إشراق فوري",
      weight: "30 مل · COD",
      pills: ["💵 الدفع عند الاستلام", "🚚 توصيل 58 ولاية", "☀️ فيتامين سي 20%", "✨ إشراق ملحوظ"],
      highlights: [
        { icon: "✨", title: "فيتامين سي 20%", text: "يُفتّح البشرة ويُعطيها إشراقاً طبيعياً مرئياً" },
        { icon: "🛡️", title: "مضاد أكسدة", text: "يحمي من أضرار أشعة الشمس والتلوث البيئي" },
        { icon: "🌿", title: "حمض الفيروليك", text: "يُثبّت فيتامين سي ويُضاعف فاعليته" },
        { icon: "⏰", title: "مضاد شيخوخة", text: "يُقلّل ظهور خطوط التعبير وعلامات الإجهاد" },
      ],
      specs: [
        ["الحجم", "30 مل"],
        ["التركيز", "فيتامين سي 20% + حمض الفيروليك"],
        ["الاستخدام", "صباحاً قبل واقي الشمس"],
        ["أنواع البشرة", "جميع الأنواع — خاصة الباهتة"],
        ["التوصيل", "58 ولاية — الدفع عند الاستلام"],
      ],
      gallery: false,
    },
    "arbutin-cream": {
      badge: "🌸 الأكثر مبيعاً",
      weight: "50 جرام · COD",
      pills: ["💵 الدفع عند الاستلام", "🚚 توصيل 58 ولاية", "🌸 أربوتين 2%", "✨ يُفتّح البقع"],
      highlights: [
        { icon: "🌸", title: "ألفا أربوتين 2%", text: "يُخفّف البقع الداكنة والكلف بشكل تدريجي وآمن" },
        { icon: "✨", title: "حمض الكوجيك", text: "يُعزّز التفتيح ويُوحّد لون البشرة بفاعلية" },
        { icon: "💧", title: "ترطيب مكثّف", text: "قوام كريمي مُرطّب — لا يُجفّف البشرة" },
        { icon: "🛡️", title: "آمن للاستخدام", text: "بديل طبيعي وآمن للهيدروكينون — مناسب يومياً" },
      ],
      specs: [
        ["الوزن", "50 جرام"],
        ["المكونات الرئيسية", "أربوتين 2%، حمض كوجيك، فيتامين سي"],
        ["الاستخدام", "صباحاً ومساءً مع واقي شمس"],
        ["أنواع البشرة", "جميع الأنواع"],
        ["التوصيل", "58 ولاية — الدفع عند الاستلام"],
      ],
      gallery: false,
    },
    "spf50-sunscreen": {
      badge: "🌞 ضروري يومياً",
      weight: "50 مل · COD",
      pills: ["💵 الدفع عند الاستلام", "🚚 توصيل 58 ولاية", "🌞 SPF 50+ PA++++", "🪶 قوام خفيف"],
      highlights: [
        { icon: "🛡️", title: "SPF 50+ PA++++", text: "حماية قصوى من أشعة UVA/UVB التي تُسبّب الشيخوخة" },
        { icon: "🪶", title: "قوام خفيف", text: "لا يُبيّض البشرة ولا يُسبّب الإفرازات الزيتية" },
        { icon: "🎨", title: "مناسب للمكياج", text: "يمكن استخدامه تحت الأساس مباشرة" },
        { icon: "🌿", title: "لجميع البشرة", text: "مناسب للبشرة الحساسة والدهنية والمختلطة" },
      ],
      specs: [
        ["الحجم", "50 مل"],
        ["معامل الحماية", "SPF 50+ · PA++++"],
        ["الاستخدام", "صباحاً — آخر خطوة في الروتين"],
        ["أنواع البشرة", "جميع الأنواع"],
        ["التوصيل", "58 ولاية — الدفع عند الاستلام"],
      ],
      gallery: false,
    },
    "ceramide-cream": {
      badge: "🛡️ يُرمّم البشرة",
      weight: "50 جرام · COD",
      pills: ["💵 الدفع عند الاستلام", "🚚 توصيل 58 ولاية", "🛡️ سيراميد + HA", "💧 ترطيب عميق"],
      highlights: [
        { icon: "🛡️", title: "سيراميد", text: "يُرمّم الحاجز الجلدي ويُقلّل فقدان رطوبة البشرة" },
        { icon: "💧", title: "هيالورونيك أسيد", text: "يمنح ترطيباً عميقاً يدوم طوال اليوم" },
        { icon: "🌿", title: "بانتينول", text: "يُهدّئ البشرة المُتهيّجة ويُخفّف الاحمرار" },
        { icon: "🤍", title: "لطيف جداً", text: "خالٍ من العطور — مثالي للبشرة الحساسة والجافة" },
      ],
      specs: [
        ["الوزن", "50 جرام"],
        ["المكونات", "سيراميد، هيالورونيك أسيد، بانتينول"],
        ["الاستخدام", "صباحاً ومساءً على بشرة نظيفة"],
        ["أنواع البشرة", "جافة، حساسة، عادية"],
        ["التوصيل", "58 ولاية — الدفع عند الاستلام"],
      ],
      gallery: false,
    },
    "rosemary-hair-oil": {
      badge: "🌿 فايرال TikTok",
      weight: "60 مل · COD",
      pills: ["💵 الدفع عند الاستلام", "🚚 توصيل 58 ولاية", "🌿 إكليل الجبل", "💪 ضد التساقط"],
      highlights: [
        { icon: "🌿", title: "إكليل الجبل", text: "مُثبَت علمياً لتحفيز نمو الشعر — يُعادل مينوكسيديل 2%" },
        { icon: "💪", title: "زيت الخروع", text: "يُقوّي بصيلات الشعر ويُقلّل التساقط المفرط" },
        { icon: "✨", title: "زيت الأرغان", text: "يُرطّب فروة الرأس ويُلمّع الشعر بشكل طبيعي" },
        { icon: "📈", title: "نتائج مرئية", text: "نمو ملحوظ بعد 4-8 أسابيع من الاستخدام المنتظم" },
      ],
      specs: [
        ["الحجم", "60 مل"],
        ["المكونات", "إكليل الجبل، خروع، أرغان"],
        ["الاستخدام", "3 مرات أسبوعياً على فروة الرأس"],
        ["النوع", "زيت جاف خفيف"],
        ["التوصيل", "58 ولاية — الدفع عند الاستلام"],
      ],
      gallery: false,
    },
    "retinol-serum": {
      badge: "🌙 روتين الليل",
      weight: "30 مل · COD",
      pills: ["💵 الدفع عند الاستلام", "🚚 توصيل 58 ولاية", "🌙 يُستخدم ليلاً", "⏰ مضاد شيخوخة"],
      highlights: [
        { icon: "⏰", title: "ريتينول 0.3%", text: "يُجدّد خلايا البشرة أثناء النوم ويُحسّن الملمس" },
        { icon: "✨", title: "مضاد تجاعيد", text: "يُقلّل ظهور الخطوط الدقيقة والتجاعيد تدريجياً" },
        { icon: "💧", title: "هيالورونيك أسيد", text: "يُعوّض الجفاف الناتج عن الريتينول ويُرطّب بعمق" },
        { icon: "🛡️", title: "تركيز مناسب للمبتدئين", text: "0.3% — فاعل دون تهيّج مفرط للبشرة الحساسة" },
      ],
      specs: [
        ["الحجم", "30 مل"],
        ["التركيز", "ريتينول 0.3%"],
        ["الاستخدام", "ليلاً فقط — مرة كل يومين للمبتدئين"],
        ["أنواع البشرة", "عادية، مختلطة، دهنية"],
        ["التوصيل", "58 ولاية — الدفع عند الاستلام"],
      ],
      gallery: false,
    },
  },

  ARENCIA_LINE: {
    href: "arencia.html",
    name: "خط Arencia Booster Shot",
    lead: "علامة كورية واحدة. 6 تركيبات — تختاري النوع حسب احتياج بشرتك.",
    priceFrom: 3900,
    mosaic: [
      "assets/products/arencia-nad-booster/hero-product.png?v=1",
      "assets/products/arencia-txa-booster/hero-product.png?v=1",
      "assets/products/arencia-retinal-booster/hero-product.png?v=1",
      "assets/products/arencia-vitamin-c-booster/hero-product.png?v=1",
    ],
    groups: [
      {
        id: "brighten",
        title: "إشراق وتوحيد اللون",
        blurb: "للبهتان والبقع الداكنة",
        productIds: ["arencia-vitamin-c-booster", "arencia-txa-booster"],
      },
      {
        id: "renew",
        title: "تجديد وحيوية",
        blurb: "للبشرة الباهتة والحساسة",
        productIds: ["arencia-nad-booster", "arencia-pdrn-booster"],
      },
      {
        id: "firm",
        title: "شد ليلي",
        blurb: "لثبات المظهر وعلامات التعب",
        productIds: ["arencia-retinal-booster"],
      },
      {
        id: "exfoliate",
        title: "تقشير وتنعيم",
        blurb: "للملمس الخشن والاحتقان",
        productIds: ["arencia-eraser-glycolic"],
      },
    ],
  },
};
