// HadeelBeauty storefront config — Algérie
window.HADEELBEAUTY_CONFIG = {
  API_BASE: "", // same-origin via nginx /api/ proxy on hadeelbeauty.store
  STORE_URL: "https://hadeelbeauty.store",

  META_PIXEL_ID: "1027331430352258",
  TIKTOK_PIXEL_ID: "",
  SNAPCHAT_PIXEL_ID: "",

  PRODUCT_META: {
    "scar-gel-tcm": {
      emoji: "✨",
      category: "ندبات · حب الشباب",
      gradient: "linear-gradient(135deg, #fff8e1, #d4a574)",
      image: "assets/products/scar-gel/hero-product.png?v=1",
    },
    "arencia-nad-booster": {
      emoji: "💜",
      category: "تجديد · بشرة باهتة",
      gradient: "linear-gradient(135deg, #f4f1fa, #c5b8e0)",
      image: "assets/products/arencia-nad-booster/hero-product.png?v=1",
    },
    "arencia-eraser-glycolic": {
      emoji: "🩶",
      category: "تقشير · مسام",
      gradient: "linear-gradient(135deg, #f6f4f1, #c8c4be)",
      image: "assets/products/arencia-eraser-glycolic/hero-product.png?v=1",
    },
    "arencia-txa-booster": {
      emoji: "🪸",
      category: "بقع · توحيد اللون",
      gradient: "linear-gradient(135deg, #fdf4f0, #e8a090)",
      image: "assets/products/arencia-txa-booster/hero-product.png?v=1",
    },
    "arencia-pdrn-booster": {
      emoji: "🌸",
      category: "تهدئة · تجديد",
      gradient: "linear-gradient(135deg, #fdf4f6, #d4a0b0)",
      image: "assets/products/arencia-pdrn-booster/hero-product.png?v=1",
    },
    "arencia-retinal-booster": {
      emoji: "🌙",
      category: "شد · ليلي",
      gradient: "linear-gradient(135deg, #fffbe8, #f0d24a)",
      image: "assets/products/arencia-retinal-booster/hero-product.png?v=1",
    },
    "arencia-vitamin-c-booster": {
      emoji: "🍋",
      category: "إشراق · تفتيح",
      gradient: "linear-gradient(135deg, #f7fbe8, #c5d45a)",
      image: "assets/products/arencia-vitamin-c-booster/hero-product.png?v=1",
    },
    "medicube-txa-niacinamide": {
      emoji: "🔴",
      category: "بقع · توحيد اللون",
      gradient: "linear-gradient(135deg, #fff1f0, #e85a5a)",
      image: "assets/products/medicube-txa-niacinamide/hero-product.png?v=1",
    },
    "medicube-vita-c": {
      emoji: "✨",
      category: "إشراق · فيتامين سي",
      gradient: "linear-gradient(135deg, #f7f1e6, #c4a15a)",
      image: "assets/products/medicube-vita-c/hero-product.png?v=1",
    },
    "medicube-hyaluronic": {
      emoji: "💧",
      category: "ترطيب · حاجز البشرة",
      gradient: "linear-gradient(135deg, #eef6fb, #5aa8d4)",
      image: "assets/products/medicube-hyaluronic/hero-product.png?v=1",
    },
    "medicube-kojic-turmeric": {
      emoji: "🍋",
      category: "تفتيح · كوجيك",
      gradient: "linear-gradient(135deg, #fffbe8, #f0d24a)",
      image: "assets/products/medicube-kojic-turmeric/hero-product.png?v=1",
    },
    "medicube-pdrn-collagen": {
      emoji: "💗",
      category: "تجديد · كولاجين",
      gradient: "linear-gradient(135deg, #fdf4f6, #e8a0b8)",
      image: "assets/products/medicube-pdrn-collagen/hero-product.png?v=1",
    },
    "anua-pdrn-hyaluron": {
      emoji: "💧",
      kicker: "PDRN",
      category: "ترطيب · PDRN",
      gradient: "linear-gradient(135deg, #eef7f6, #7eb8b0)",
      image: "assets/products/anua-pdrn-hyaluron/hero-product.png?v=1",
    },
    "anua-niacinamide-txa": {
      emoji: "🔴",
      kicker: "TXA",
      category: "بقع · توحيد اللون",
      gradient: "linear-gradient(135deg, #fff1f0, #e85a5a)",
      image: "assets/products/anua-niacinamide-txa/hero-product.png?v=1",
    },
    "althea-345-mist": {
      emoji: "💨",
      kicker: "رذاذ",
      category: "ترطيب · تهدئة",
      gradient: "linear-gradient(135deg, #f7f6f3, #d8d4cc)",
      image: "assets/products/althea-345-mist/hero-product.png?v=1",
    },
    "althea-345-cream": {
      emoji: "🤍",
      kicker: "كريم",
      category: "تهدئة · حاجز البشرة",
      gradient: "linear-gradient(135deg, #fbfaf7, #cfc9c0)",
      image: "assets/products/althea-345-cream/hero-product.png?v=1",
    },
    "joseon-relief-sun": {
      emoji: "☀️",
      kicker: "أرز",
      category: "واقي شمس · ترطيب",
      gradient: "linear-gradient(135deg, #fff9f0, #e8d5b0)",
      image: "assets/products/joseon-relief-sun/hero-product.png?v=1",
    },
    "joseon-aqua-fresh": {
      emoji: "🌊",
      kicker: "Aqua-fresh",
      category: "واقي شمس · خفيف",
      gradient: "linear-gradient(135deg, #eef6fb, #7eb8d4)",
      image: "assets/products/joseon-aqua-fresh/hero-product.png?v=1",
    },
    "joseon-revive-eye": {
      emoji: "🌙",
      kicker: "ريتينال",
      category: "محيط العين · ليلي",
      gradient: "linear-gradient(135deg, #f7f3ea, #d4c4a0)",
      image: "assets/products/joseon-revive-eye/hero-product.png?v=1",
    },
    "niacinamide-serum": {
      emoji: "💧",
      category: "مسام · بشرة دهنية",
      gradient: "linear-gradient(135deg, #fdf6f3, #d1717f)",
      image: "assets/assets/products/niacinamide-serum/hero-product.png",
    },
    "vitamin-c-serum": {
      emoji: "☀️",
      category: "تفتيح · إشراق",
      gradient: "linear-gradient(135deg, #fffdf0, #ffaa00)",
      image: "assets/assets/products/vitamin-c-serum/hero-product.png",
    },
    "arbutin-cream": {
      emoji: "🌸",
      category: "تفتيح · بقع داكنة",
      gradient: "linear-gradient(135deg, #fdf8f5, #e8aabb)",
      image: "assets/assets/products/arbutin-cream/hero-product.png",
    },
    "spf50-sunscreen": {
      emoji: "🌞",
      category: "حماية · واقي شمس",
      gradient: "linear-gradient(135deg, #fff9f0, #ffd966)",
      image: "assets/assets/products/spf50-sunscreen/hero-product.png",
    },
    "ceramide-cream": {
      emoji: "🛡️",
      category: "ترطيب · بشرة جافة",
      gradient: "linear-gradient(135deg, #f0f7f6, #7eb8b0)",
      image: "assets/assets/products/ceramide-cream/hero-product.png",
    },
    "rosemary-hair-oil": {
      emoji: "🌿",
      category: "شعر · تساقط",
      gradient: "linear-gradient(135deg, #f0f7ee, #40916c)",
      image: "assets/assets/products/rosemary-hair-oil/hero-product.png",
    },
    "retinol-serum": {
      emoji: "🌙",
      category: "مضاد شيخوخة · ليلي",
      gradient: "linear-gradient(135deg, #1a1a2e, #7b2d8b)",
      image: "assets/assets/products/retinol-serum/hero-product.png",
    },
  },

  PRODUCT_PROFILES: {
    "scar-gel-tcm": {
      badge: "✨ الأكثر طلباً",
      weight: "30 جرام · COD",
      pills: ["💵 الدفع عند الاستلام", "📦 افحصي المنتج قبل الدفع", "🚚 توصيل 58 ولاية", "🌿 تركيبة TCM لطيفة"],
      highlights: [
        { icon: "🛡️", title: "حماية", text: "يساعد على تقليل ظهور الندبات بعد الجروح والعمليات" },
        { icon: "✨", title: "توحيد اللون", text: "نياسيناميد وأربوتين لدعم مظهر أكثر توازناً" },
        { icon: "💧", title: "ترطيب", text: "هيالورونات الصوديوم لترطيب دون دهون" },
        { icon: "🌿", title: "لطيف", text: "قوام شفاف سريع الامتصاص — لجميع أنواع البشرة" },
      ],
      specs: [
        ["الوزن الصافي", "30 جرام"],
        ["النوع", "جل شفاف"],
        ["الاستخدام", "مساءً — يومي"],
        ["أنواع البشرة", "جميع الأنواع"],
        ["المكونات البارزة", "سنتيلا آسياتيكا، نياسيناميد، أربوتين"],
        ["التوصيل", "58 ولاية — الدفع عند الاستلام"],
      ],
      howto: {
        src: "assets/products/scar-gel/v10-howto.png?v=2",
        alt: "طريقة الاستعمال — تنظيف، طبقة رقيقة، تدليك خفيف مساءً",
      },
      gallery: true,
    },
    "arencia-nad-booster": {
      badge: "💜 NAD+ Booster",
      weight: "30 مل · COD",
      pills: ["💵 الدفع عند الاستلام", "📦 افحصي قبل الدفع", "🚚 توصيل 58 ولاية", "💜 NAD+ 5%"],
      highlights: [
        { icon: "💜", title: "NAD+ 5%", text: "يدعم مظهر بشرة أكثر حيوية ونشاطاً — خاصة البشرة الباهتة والتعبة" },
        { icon: "🌿", title: "ريسفيراترول", text: "مضاد أكسدة نباتي يساعد على حماية مظهر البشرة من الإجهاد" },
        { icon: "✨", title: "ببتيدات", text: "تدعم مظهراً أكثر نعومة وثباتاً مع الاستعمال المنتظم" },
        { icon: "👁️", title: "وجه ومحيط العين", text: "مرطب خفيف للوجه ومحيط العين — صباحاً ومساءً" },
      ],
      specs: [
        ["الحجم", "30 مل"],
        ["المكونات البارزة", "NAD+ 5%، ريسفيراترول، ببتيدات"],
        ["الاستخدام", "صباحاً ومساءً بعد التنظيف"],
        ["الأنسب لـ", "البشرة الباهتة والتعبة"],
        ["التوصيل", "58 ولاية — الدفع عند الاستلام"],
      ],
      gallery: false,
    },
    "arencia-eraser-glycolic": {
      badge: "🩶 Eraser Shot",
      weight: "30 مل · COD",
      pills: ["💵 الدفع عند الاستلام", "📦 افحصي قبل الدفع", "🚚 توصيل 58 ولاية", "🩶 تقشير لطيف"],
      highlights: [
        { icon: "🩶", title: "حمض الجليكوليك (AHA)", text: "يقشّر الطبقة السطحية بلطف وينعّم ملمس البشرة الخشن" },
        { icon: "🔬", title: "BHA", text: "يساعد على تخفيف مظهر الاحتقان والرؤوس السوداء داخل المسام" },
        { icon: "🌿", title: "تهدئة", text: "تركيبة مخصّصة لتنعيم الملمس دون وعد بإزالة حب الشباب فوراً" },
        { icon: "🌙", title: "استعمال ليلي", text: "ابدئي كل ليلة أو ليلتين، ودائماً واقي شمس في النهار" },
      ],
      specs: [
        ["الحجم", "30 مل"],
        ["المكونات البارزة", "حمض الجليكوليك، BHA"],
        ["الاستخدام", "ليلاً — ابدئي تدريجياً"],
        ["الأنسب لـ", "الملمس الخشن والاحتقان"],
        ["تنبيه", "لا تخلطيه مع ريتينال أو فيتامين سي في نفس الروتين"],
        ["التوصيل", "58 ولاية — الدفع عند الاستلام"],
      ],
      gallery: false,
    },
    "arencia-txa-booster": {
      badge: "🪸 TXA Booster",
      weight: "30 مل · COD",
      pills: ["💵 الدفع عند الاستلام", "📦 افحصي قبل الدفع", "🚚 توصيل 58 ولاية", "🪸 TXA 5%"],
      highlights: [
        { icon: "🪸", title: "TXA 5%", text: "يساعد على تلطيف مظهر البقع الداكنة وتفاوت اللون تدريجياً" },
        { icon: "✨", title: "ببتيدات", text: "تدعم مظهراً أكثر نعومة ووضوحاً مع الاستعمال المنتظم" },
        { icon: "🌸", title: "توحيد اللون", text: "للتصبغات وآثار البقع — بلا ادّعاء محو فوري" },
        { icon: "👁️", title: "وجه ومحيط العين", text: "خفيف على البشرة — صباحاً ومساءً مع واقي شمس" },
      ],
      specs: [
        ["الحجم", "30 مل"],
        ["المكونات البارزة", "TXA 5%، ببتيدات"],
        ["الاستخدام", "صباحاً ومساءً — مع واقي شمس نهاراً"],
        ["الأنسب لـ", "البقع الداكنة وتفاوت اللون"],
        ["التوصيل", "58 ولاية — الدفع عند الاستلام"],
      ],
      gallery: false,
    },
    "arencia-pdrn-booster": {
      badge: "🌸 PDRN Booster",
      weight: "30 مل · COD",
      pills: ["💵 الدفع عند الاستلام", "📦 افحصي قبل الدفع", "🚚 توصيل 58 ولاية", "🌸 مناسب للحساسة"],
      highlights: [
        { icon: "🌸", title: "Rosy-PDRN 5%", text: "يدعم مظهر بشرة مرتاحة وأكثر تماسكًا بعد الإجهاد أو الاحمرار" },
        { icon: "💧", title: "ببتيدات", text: "ترطيب ودعْم لمظهر أكثر نعومة وثباتاً" },
        { icon: "🌿", title: "تهدئة", text: "مناسب للبشرة الحساسة والمعرّضة للاحمرار" },
        { icon: "👁️", title: "وجه ومحيط العين", text: "مرطب يومي لطيف — صباحاً ومساءً" },
      ],
      specs: [
        ["الحجم", "30 مل"],
        ["المكونات البارزة", "Rosy-PDRN 5%، ببتيدات"],
        ["الاستخدام", "صباحاً ومساءً بعد التنظيف"],
        ["الأنسب لـ", "البشرة الحساسة والاحمرار"],
        ["التوصيل", "58 ولاية — الدفع عند الاستلام"],
      ],
      gallery: false,
    },
    "arencia-retinal-booster": {
      badge: "🌙 Retinal Booster",
      weight: "30 مل · COD",
      pills: ["💵 الدفع عند الاستلام", "📦 افحصي قبل الدفع", "🚚 توصيل 58 ولاية", "🌙 استعمال ليلي"],
      highlights: [
        { icon: "🌙", title: "ريتينال 2%", text: "مشتق فيتامين A يدعم مظهر أكثر نعومة وثباتاً مع الروتين الليلي" },
        { icon: "☕", title: "كافيين", text: "يساعد على تخفيف مظهر الانتفاخ والتعب حول العين" },
        { icon: "✨", title: "شدّ لطيف", text: "ليس وصفة طبية — يدعم مرونة المظهر تدريجياً" },
        { icon: "🛡️", title: "ابدئي ببطء", text: "ليلة بعد ليلة حتى تعتاد البشرة — وواقي شمس في الصباح" },
      ],
      specs: [
        ["الحجم", "30 مل"],
        ["المكونات البارزة", "ريتينال (مركب 2%)، كافيين"],
        ["الاستخدام", "ليلاً فقط — ابدئي كل ليلتين"],
        ["الأنسب لـ", "فقدان الثبات وعلامات التعب"],
        ["تنبيه", "لا تخلطيه مع فيتامين سي أو أحماض التقشير في نفس الروتين"],
        ["التوصيل", "58 ولاية — الدفع عند الاستلام"],
      ],
      gallery: false,
    },
    "arencia-vitamin-c-booster": {
      badge: "🍋 Vitamin C Booster",
      weight: "30 مل · COD",
      pills: ["💵 الدفع عند الاستلام", "📦 افحصي قبل الدفع", "🚚 توصيل 58 ولاية", "🍋 فيتامين سي 5%"],
      highlights: [
        { icon: "🍋", title: "فيتامين سي 5%", text: "يساعد على إشراق البشرة وتلطيف مظهر البهتان" },
        { icon: "✨", title: "جلوتاثيون", text: "مضاد أكسدة يدعم وضوح اللون ومظهراً أكثر إشراقاً" },
        { icon: "☀️", title: "روتين الصباح", text: "يُفضّل صباحاً ثم واقي شمس — لا تخلطيه مع ريتينال" },
        { icon: "👁️", title: "وجه ومحيط العين", text: "مرطب خفيف للوجه ومحيط العين" },
      ],
      specs: [
        ["الحجم", "30 مل"],
        ["المكونات البارزة", "فيتامين سي 5%، جلوتاثيون"],
        ["الاستخدام", "صباحاً قبل واقي الشمس"],
        ["الأنسب لـ", "البشرة الباهتة وقلة الإشراق"],
        ["تنبيه", "لا تخلطيه مع ريتينال أو أحماض التقشير في نفس الروتين"],
        ["التوصيل", "58 ولاية — الدفع عند الاستلام"],
      ],
      gallery: false,
    },
    "medicube-txa-niacinamide": {
      badge: "🔴 medicube TXA",
      weight: "55 جم · COD",
      pills: ["💵 الدفع عند الاستلام", "📦 افحصي قبل الدفع", "🚚 توصيل 58 ولاية", "🔴 TXA + نياسيناميد 5%"],
      highlights: [
        { icon: "🔴", title: "TXA", text: "يساعد على تلطيف مظهر البقع الداكنة وتفاوت اللون تدريجياً" },
        { icon: "✨", title: "نياسيناميد 5%", text: "يدعم وضوح اللون ومظهراً أكثر توازناً" },
        { icon: "💊", title: "كريم كبسولات", text: "تخلطين الكبسولة مع الجل حسب احتياج بشرتك" },
        { icon: "☀️", title: "واقي شمس", text: "صباحاً ومساءً — ودائماً واقي شمس في النهار" },
      ],
      specs: [
        ["الوزن", "55 جم"],
        ["المكونات البارزة", "TXA، نياسيناميد 5%"],
        ["الاستخدام", "صباحاً ومساءً بعد السيروم"],
        ["الأنسب لـ", "البقع الداكنة وتفاوت اللون"],
        ["التوصيل", "58 ولاية — الدفع عند الاستلام"],
      ],
      gallery: false,
    },
    "medicube-vita-c": {
      badge: "✨ medicube Vita C",
      weight: "55 جم · COD",
      pills: ["💵 الدفع عند الاستلام", "📦 افحصي قبل الدفع", "🚚 توصيل 58 ولاية", "✨ فيتامين سي"],
      highlights: [
        { icon: "✨", title: "فيتامين سي", text: "مشتقات فيتامين سي داخل كبسولات لدعم إشراق البشرة" },
        { icon: "💧", title: "ماء فيتامين 50%", text: "قاعدة مرطّبة تساعد على مظهر أكثر نضارة" },
        { icon: "🌸", title: "نياسيناميد 5%", text: "يدعم توحيد اللون مع الإشراق" },
        { icon: "☀️", title: "صباحاً مع واقي شمس", text: "فيتامين سي يُفضّل مع حماية من الشمس" },
      ],
      specs: [
        ["الوزن", "55 جم"],
        ["المكونات البارزة", "فيتامين سي، نياسيناميد 5%"],
        ["الاستخدام", "صباحاً ومساءً — واقي شمس نهاراً"],
        ["الأنسب لـ", "البشرة الباهتة وقلة الإشراق"],
        ["التوصيل", "58 ولاية — الدفع عند الاستلام"],
      ],
      gallery: false,
    },
    "medicube-hyaluronic": {
      badge: "💧 medicube Hyaluronic",
      weight: "55 جم · COD",
      pills: ["💵 الدفع عند الاستلام", "📦 افحصي قبل الدفع", "🚚 توصيل 58 ولاية", "💧 ترطيب"],
      highlights: [
        { icon: "💧", title: "هيالورونات", text: "ترطيب لطيف يساعد البشرة تبان مرتاحة أكثر" },
        { icon: "🌿", title: "بانتينول", text: "يدعم مظهر الحاجز الجلدي ويرطّب دون ثقل" },
        { icon: "🤍", title: "الألطف في الخط", text: "مناسب إذا هدفك الترطيب قبل أي تفتيح قوي" },
        { icon: "💊", title: "كريم كبسولات", text: "تخلطين النسبة حسب جفاف بشرتك" },
      ],
      specs: [
        ["الوزن", "55 جم"],
        ["المكونات البارزة", "هيالورونات الصوديوم، بانتينول"],
        ["الاستخدام", "صباحاً ومساءً على بشرة نظيفة"],
        ["الأنسب لـ", "الجفاف وقلة الترطيب"],
        ["التوصيل", "58 ولاية — الدفع عند الاستلام"],
      ],
      gallery: false,
    },
    "medicube-kojic-turmeric": {
      badge: "🍋 medicube Kojic",
      weight: "53 جم · COD",
      pills: ["💵 الدفع عند الاستلام", "📦 افحصي قبل الدفع", "🚚 توصيل 58 ولاية", "🍋 كوجيك + كركم"],
      highlights: [
        { icon: "🍋", title: "حمض الكوجيك", text: "يساعد على تلطيف مظهر البهتان والبقع الخفيفة" },
        { icon: "🌿", title: "كركم", text: "مضاد أكسدة نباتي لدعم مظهر بشرة أوضح" },
        { icon: "✨", title: "نياسيناميد 5%", text: "يدعم توحيد اللون مع التفتيح اللطيف" },
        { icon: "☀️", title: "واقي شمس", text: "أي روتين تفتيح يحتاج حماية نهارية" },
      ],
      specs: [
        ["الوزن", "53 جم"],
        ["المكونات البارزة", "حمض الكوجيك، كركم، نياسيناميد 5%"],
        ["الاستخدام", "صباحاً ومساءً مع واقي شمس"],
        ["الأنسب لـ", "البشرة الباهتة والبقع الخفيفة"],
        ["التوصيل", "58 ولاية — الدفع عند الاستلام"],
      ],
      gallery: false,
    },
    "medicube-pdrn-collagen": {
      badge: "💗 medicube PDRN",
      weight: "55 جم · COD",
      pills: ["💵 الدفع عند الاستلام", "📦 افحصي قبل الدفع", "🚚 توصيل 58 ولاية", "💗 PDRN"],
      highlights: [
        { icon: "💗", title: "PDRN", text: "يدعم مظهر بشرة أكثر تماسكًا بعد الإجهاد" },
        { icon: "✨", title: "نياسيناميد 5%", text: "وضوح لون مع تجديد المظهر" },
        { icon: "💊", title: "كولاجين وردي", text: "كريم كبسولات لروتين يومي لطيف" },
        { icon: "🤍", title: "للبشرة المتعبة", text: "ليس بديلاً عن إجراءات طبية — يدعم المظهر تدريجياً" },
      ],
      specs: [
        ["الوزن", "55 جم"],
        ["المكونات البارزة", "PDRN، نياسيناميد 5%"],
        ["الاستخدام", "صباحاً ومساءً بعد السيروم"],
        ["الأنسب لـ", "فقدان التماسك وعلامات التعب"],
        ["التوصيل", "58 ولاية — الدفع عند الاستلام"],
      ],
      gallery: false,
    },
    "anua-pdrn-hyaluron": {
      badge: "💧 Anua PDRN",
      weight: "60 مل · COD",
      pills: ["💵 الدفع عند الاستلام", "📦 افحصي قبل الدفع", "🚚 توصيل 58 ولاية", "💧 PDRN + هيالورون"],
      highlights: [
        { icon: "💧", title: "PDRN", text: "يدعم مظهر بشرة مرتاحة وأكثر امتلاءً مع الترطيب اليومي" },
        { icon: "✨", title: "هيالورونيك", text: "ترطيب لطيف يساعد البشرة تبان أنعم دون لزاجة" },
        { icon: "🤍", title: "آخر خطوة", text: "كريم خفيف صباحاً ومساءً بعد السيروم — تحت المكياج" },
        { icon: "🌿", title: "قوام حريري", text: "يمتص بسرعة ولا يكوّم تحت واقي الشمس" },
      ],
      specs: [
        ["الحجم", "60 مل"],
        ["المكونات البارزة", "PDRN، هيالورونيك، كولاجين محلّل"],
        ["الاستخدام", "صباحاً ومساءً — آخر خطوة قبل واقي الشمس"],
        ["الأنسب لـ", "الجفاف وقلة النضارة"],
        ["التوصيل", "58 ولاية — الدفع عند الاستلام"],
      ],
      gallery: false,
    },
    "anua-niacinamide-txa": {
      badge: "🔴 Anua 10+ TXA",
      weight: "30 مل · COD",
      pills: ["💵 الدفع عند الاستلام", "📦 افحصي قبل الدفع", "🚚 توصيل 58 ولاية", "🔴 نياسيناميد 10% + TXA 4%"],
      highlights: [
        { icon: "🔴", title: "TXA 4%", text: "يساعد على تلطيف مظهر البقع الداكنة وتفاوت اللون تدريجياً" },
        { icon: "✨", title: "نياسيناميد 10%", text: "يدعم وضوح اللون ومظهراً أكثر توازناً" },
        { icon: "🌸", title: "أربوتين", text: "يدعم تلطيف مظهر البهتان مع الاستعمال المنتظم" },
        { icon: "☀️", title: "واقي شمس", text: "صباحاً ومساءً بعد التونر — ودائماً واقي شمس في النهار" },
      ],
      specs: [
        ["الحجم", "30 مل"],
        ["المكونات البارزة", "نياسيناميد 10%، TXA 4%، أربوتين"],
        ["الاستخدام", "صباحاً ومساءً قبل المرطب — مع واقي شمس نهاراً"],
        ["الأنسب لـ", "البقع الداكنة وتفاوت اللون"],
        ["التوصيل", "58 ولاية — الدفع عند الاستلام"],
      ],
      gallery: false,
    },
    "althea-345-mist": {
      badge: "💨 Dr. Althea Mist",
      weight: "60 مل · COD",
      pills: ["💵 الدفع عند الاستلام", "📦 افحصي قبل الدفع", "🚚 توصيل 58 ولاية", "💨 رذاذ كريمي"],
      highlights: [
        { icon: "💨", title: "رذاذ كريمي", text: "ترطيب خفيف بين خطوات الروتين أو فوق المكياج خلال اليوم" },
        { icon: "🌾", title: "ماء نخالة الأرز", text: "قاعدة مرطّبة تساعد البشرة تبان مرتاحة أكثر" },
        { icon: "🌿", title: "بانتينول وسنتيلا", text: "يدعمان مظهر بشرة هادئة بعد الجفاف أو الاحمرار الخفيف" },
        { icon: "🤲", title: "رجّي قبل الاستعمال", text: "على بعد 20–30 سم مع إغلاق العينين ثم ربّتي بلطف" },
      ],
      specs: [
        ["الحجم", "60 مل"],
        ["المكونات البارزة", "ماء نخالة الأرز، هيالورونيك، بانتينول، سنتيلا"],
        ["الاستخدام", "بعد التنظيف، بين الطبقات، أو خلال اليوم"],
        ["الأنسب لـ", "الجفاف والشدّ خلال اليوم"],
        ["التوصيل", "58 ولاية — الدفع عند الاستلام"],
      ],
      gallery: false,
    },
    "althea-345-cream": {
      badge: "🤍 Dr. Althea 345",
      weight: "50 مل · COD",
      pills: ["💵 الدفع عند الاستلام", "📦 افحصي قبل الدفع", "🚚 توصيل 58 ولاية", "🤍 خالٍ من العطر"],
      highlights: [
        { icon: "🤍", title: "تركيبة 345", text: "3 لآثار البثور، 4 للترطيب، 5 للتهدئة — كريم جل خفيف" },
        { icon: "✨", title: "نياسيناميد", text: "يدعم وضوح اللون ومظهراً أكثر توازناً بعد آثار البثور" },
        { icon: "🌿", title: "بانتينول وسنتيلا", text: "يلطّفان مظهر الاحمرار ويدعمان الحاجز الجلدي" },
        { icon: "💧", title: "خالٍ من العطر", text: "صباحاً ومساءً على بشرة نظيفة — ليس علاجاً طبياً للحبوب" },
      ],
      specs: [
        ["الحجم", "50 مل"],
        ["المكونات البارزة", "نياسيناميد، بانتينول، سنتيلا، سيراميد"],
        ["الاستخدام", "صباحاً ومساءً بعد السيروم"],
        ["الأنسب لـ", "البشرة الحساسة وآثار البثور"],
        ["التوصيل", "58 ولاية — الدفع عند الاستلام"],
      ],
      gallery: false,
    },
    "joseon-relief-sun": {
      badge: "☀️ Joseon Relief Sun",
      weight: "50 مل · COD",
      pills: ["💵 الدفع عند الاستلام", "📦 افحصي قبل الدفع", "🚚 توصيل 58 ولاية", "☀️ SPF50+ PA++++"],
      highlights: [
        { icon: "☀️", title: "SPF50+ PA++++", text: "حماية يومية واسعة الطيف — آخر خطوة صباحاً" },
        { icon: "🌾", title: "أرز + بروبيوتيك", text: "قوام مرطّب أنسب للبشرة العادية إلى الجافة والحساسة" },
        { icon: "🤍", title: "بدون عطر", text: "واقي شمس كيميائي خفيف — ليس مرطباً بديلاً عن الكريم" },
        { icon: "🔁", title: "أعيدي التطبيق", text: "كمية كافية للوجه والرقبة، وأعيدي كل ساعتين عند الخروج" },
      ],
      specs: [
        ["الحجم", "50 مل"],
        ["الحماية", "SPF50+ PA++++"],
        ["الاستخدام", "صباحاً — آخر خطوة قبل المكياج"],
        ["الأنسب لـ", "البشرة العادية والجافة والحساسة"],
        ["التوصيل", "58 ولاية — الدفع عند الاستلام"],
      ],
      gallery: false,
    },
    "joseon-aqua-fresh": {
      badge: "🌊 Joseon Aqua-fresh",
      weight: "50 مل · COD",
      pills: ["💵 الدفع عند الاستلام", "📦 افحصي قبل الدفع", "🚚 توصيل 58 ولاية", "🌊 SPF50+ خفيف"],
      highlights: [
        { icon: "🌊", title: "قوام جل مائي", text: "أخف من Relief Sun الأصلي — لمسة أجف أنسب للبشرة المختلطة والدهنية" },
        { icon: "☀️", title: "SPF50+ PA++++", text: "نفس مستوى الحماية مع أرز وفيتامين B5 (بانتينول)" },
        { icon: "💧", title: "حاجز لطيف", text: "بانتينول وسيراميد يدعمان مظهر بشرة مرتاحة تحت الشمس" },
        { icon: "🔁", title: "أعيدي التطبيق", text: "آخر خطوة صباحاً — وأعيدي عند التعرّض الطويل للشمس" },
      ],
      specs: [
        ["الحجم", "50 مل"],
        ["الحماية", "SPF50+ PA++++"],
        ["الاستخدام", "صباحاً — آخر خطوة قبل المكياج"],
        ["الأنسب لـ", "البشرة المختلطة والدهنية"],
        ["التوصيل", "58 ولاية — الدفع عند الاستلام"],
      ],
      gallery: false,
    },
    "joseon-revive-eye": {
      badge: "🌙 Joseon Revive Eye",
      weight: "30 مل · COD",
      pills: ["💵 الدفع عند الاستلام", "📦 افحصي قبل الدفع", "🚚 توصيل 58 ولاية", "🌙 جينسنغ + ريتينال"],
      highlights: [
        { icon: "🌙", title: "ريتينال", text: "يدعم مظهر خطوط أدق ونعومة حول العين مع الروتين الليلي" },
        { icon: "🌿", title: "جينسنغ", text: "ترطيب لطيف لمحيط العين المتعبة" },
        { icon: "🛡️", title: "ابدئي ببطء", text: "كل ليلتين حتى تعتاد البشرة — لا تخلطيه مع أحماض التقشير" },
        { icon: "☀️", title: "واقي شمس صباحاً", text: "الريتينال يزيد حساسية الشمس. غير مناسب أثناء الحمل" },
      ],
      specs: [
        ["الحجم", "30 مل"],
        ["المكونات البارزة", "جينسنغ، ريتينال"],
        ["الاستخدام", "ليلاً على محيط العين — ابدئي تدريجياً"],
        ["الأنسب لـ", "علامات التعب والخطوط الدقيقة حول العين"],
        ["تنبيه", "تجنّبيه أثناء الحمل — لا تخلطيه مع AHA/BHA"],
        ["التوصيل", "58 ولاية — الدفع عند الاستلام"],
      ],
      gallery: false,
    },
    "niacinamide-serum": {
      badge: "🔥 ترند الجزائر",
      weight: "30 مل · COD",
      pills: ["💵 الدفع عند الاستلام", "🚚 توصيل 58 ولاية", "💧 نياسيناميد 10%", "🌿 مناسب للبشرة الدهنية"],
      highlights: [
        { icon: "🔬", title: "نياسيناميد 10%", text: "يُضيّق المسام ويُقلّل الإفرازات الزيتية بشكل ملحوظ" },
        { icon: "✨", title: "توحيد اللون", text: "يُخفّف البقع الداكنة وآثار حب الشباب تدريجياً" },
        { icon: "🛡️", title: "زنك 1%", text: "يُهدّئ الالتهابات ويُقلّل احمرار البشرة" },
        { icon: "💧", title: "قوام خفيف", text: "سريع الامتصاص — لا يُثقّل البشرة ولا يُسبّب الدهون" },
      ],
      specs: [
        ["الحجم", "30 مل"],
        ["التركيز", "نياسيناميد 10% + زنك 1%"],
        ["الاستخدام", "صباحاً ومساءً بعد التنظيف"],
        ["أنواع البشرة", "دهنية، مختلطة، شبابية"],
        ["التوصيل", "58 ولاية — الدفع عند الاستلام"],
      ],
      gallery: false,
    },
    "vitamin-c-serum": {
      badge: "☀️ إشراق فوري",
      weight: "30 مل · COD",
      pills: ["💵 الدفع عند الاستلام", "🚚 توصيل 58 ولاية", "☀️ فيتامين سي 20%", "✨ إشراق ملحوظ"],
      highlights: [
        { icon: "✨", title: "فيتامين سي 20%", text: "يُفتّح البشرة ويُعطيها إشراقاً طبيعياً مرئياً" },
        { icon: "🛡️", title: "مضاد أكسدة", text: "يحمي من أضرار أشعة الشمس والتلوث البيئي" },
        { icon: "🌿", title: "حمض الفيروليك", text: "يُثبّت فيتامين سي ويُضاعف فاعليته" },
        { icon: "⏰", title: "مضاد شيخوخة", text: "يُقلّل ظهور خطوط التعبير وعلامات الإجهاد" },
      ],
      specs: [
        ["الحجم", "30 مل"],
        ["التركيز", "فيتامين سي 20% + حمض الفيروليك"],
        ["الاستخدام", "صباحاً قبل واقي الشمس"],
        ["أنواع البشرة", "جميع الأنواع — خاصة الباهتة"],
        ["التوصيل", "58 ولاية — الدفع عند الاستلام"],
      ],
      gallery: false,
    },
    "arbutin-cream": {
      badge: "🌸 الأكثر مبيعاً",
      weight: "50 جرام · COD",
      pills: ["💵 الدفع عند الاستلام", "🚚 توصيل 58 ولاية", "🌸 أربوتين 2%", "✨ يُفتّح البقع"],
      highlights: [
        { icon: "🌸", title: "ألفا أربوتين 2%", text: "يُخفّف البقع الداكنة والكلف بشكل تدريجي وآمن" },
        { icon: "✨", title: "حمض الكوجيك", text: "يُعزّز التفتيح ويُوحّد لون البشرة بفاعلية" },
        { icon: "💧", title: "ترطيب مكثّف", text: "قوام كريمي مُرطّب — لا يُجفّف البشرة" },
        { icon: "🛡️", title: "آمن للاستخدام", text: "بديل طبيعي وآمن للهيدروكينون — مناسب يومياً" },
      ],
      specs: [
        ["الوزن", "50 جرام"],
        ["المكونات الرئيسية", "أربوتين 2%، حمض كوجيك، فيتامين سي"],
        ["الاستخدام", "صباحاً ومساءً مع واقي شمس"],
        ["أنواع البشرة", "جميع الأنواع"],
        ["التوصيل", "58 ولاية — الدفع عند الاستلام"],
      ],
      gallery: false,
    },
    "spf50-sunscreen": {
      badge: "🌞 ضروري يومياً",
      weight: "50 مل · COD",
      pills: ["💵 الدفع عند الاستلام", "🚚 توصيل 58 ولاية", "🌞 SPF 50+ PA++++", "🪶 قوام خفيف"],
      highlights: [
        { icon: "🛡️", title: "SPF 50+ PA++++", text: "حماية قصوى من أشعة UVA/UVB التي تُسبّب الشيخوخة" },
        { icon: "🪶", title: "قوام خفيف", text: "لا يُبيّض البشرة ولا يُسبّب الإفرازات الزيتية" },
        { icon: "🎨", title: "مناسب للمكياج", text: "يمكن استخدامه تحت الأساس مباشرة" },
        { icon: "🌿", title: "لجميع البشرة", text: "مناسب للبشرة الحساسة والدهنية والمختلطة" },
      ],
      specs: [
        ["الحجم", "50 مل"],
        ["معامل الحماية", "SPF 50+ · PA++++"],
        ["الاستخدام", "صباحاً — آخر خطوة في الروتين"],
        ["أنواع البشرة", "جميع الأنواع"],
        ["التوصيل", "58 ولاية — الدفع عند الاستلام"],
      ],
      gallery: false,
    },
    "ceramide-cream": {
      badge: "🛡️ يُرمّم البشرة",
      weight: "50 جرام · COD",
      pills: ["💵 الدفع عند الاستلام", "🚚 توصيل 58 ولاية", "🛡️ سيراميد + HA", "💧 ترطيب عميق"],
      highlights: [
        { icon: "🛡️", title: "سيراميد", text: "يُرمّم الحاجز الجلدي ويُقلّل فقدان رطوبة البشرة" },
        { icon: "💧", title: "هيالورونيك أسيد", text: "يمنح ترطيباً عميقاً يدوم طوال اليوم" },
        { icon: "🌿", title: "بانتينول", text: "يُهدّئ البشرة المُتهيّجة ويُخفّف الاحمرار" },
        { icon: "🤍", title: "لطيف جداً", text: "خالٍ من العطور — مثالي للبشرة الحساسة والجافة" },
      ],
      specs: [
        ["الوزن", "50 جرام"],
        ["المكونات", "سيراميد، هيالورونيك أسيد، بانتينول"],
        ["الاستخدام", "صباحاً ومساءً على بشرة نظيفة"],
        ["أنواع البشرة", "جافة، حساسة، عادية"],
        ["التوصيل", "58 ولاية — الدفع عند الاستلام"],
      ],
      gallery: false,
    },
    "rosemary-hair-oil": {
      badge: "🌿 فايرال TikTok",
      weight: "60 مل · COD",
      pills: ["💵 الدفع عند الاستلام", "🚚 توصيل 58 ولاية", "🌿 إكليل الجبل", "💪 ضد التساقط"],
      highlights: [
        { icon: "🌿", title: "إكليل الجبل", text: "مُثبَت علمياً لتحفيز نمو الشعر — يُعادل مينوكسيديل 2%" },
        { icon: "💪", title: "زيت الخروع", text: "يُقوّي بصيلات الشعر ويُقلّل التساقط المفرط" },
        { icon: "✨", title: "زيت الأرغان", text: "يُرطّب فروة الرأس ويُلمّع الشعر بشكل طبيعي" },
        { icon: "📈", title: "نتائج مرئية", text: "نمو ملحوظ بعد 4-8 أسابيع من الاستخدام المنتظم" },
      ],
      specs: [
        ["الحجم", "60 مل"],
        ["المكونات", "إكليل الجبل، خروع، أرغان"],
        ["الاستخدام", "3 مرات أسبوعياً على فروة الرأس"],
        ["النوع", "زيت جاف خفيف"],
        ["التوصيل", "58 ولاية — الدفع عند الاستلام"],
      ],
      gallery: false,
    },
    "retinol-serum": {
      badge: "🌙 روتين الليل",
      weight: "30 مل · COD",
      pills: ["💵 الدفع عند الاستلام", "🚚 توصيل 58 ولاية", "🌙 يُستخدم ليلاً", "⏰ مضاد شيخوخة"],
      highlights: [
        { icon: "⏰", title: "ريتينول 0.3%", text: "يُجدّد خلايا البشرة أثناء النوم ويُحسّن الملمس" },
        { icon: "✨", title: "مضاد تجاعيد", text: "يُقلّل ظهور الخطوط الدقيقة والتجاعيد تدريجياً" },
        { icon: "💧", title: "هيالورونيك أسيد", text: "يُعوّض الجفاف الناتج عن الريتينول ويُرطّب بعمق" },
        { icon: "🛡️", title: "تركيز مناسب للمبتدئين", text: "0.3% — فاعل دون تهيّج مفرط للبشرة الحساسة" },
      ],
      specs: [
        ["الحجم", "30 مل"],
        ["التركيز", "ريتينول 0.3%"],
        ["الاستخدام", "ليلاً فقط — مرة كل يومين للمبتدئين"],
        ["أنواع البشرة", "عادية، مختلطة، دهنية"],
        ["التوصيل", "58 ولاية — الدفع عند الاستلام"],
      ],
      gallery: false,
    },
  },

  ARENCIA_LINE: {
    href: "arencia.html",
    name: "خط Arencia Booster Shot",
    badge: "Arencia · 6 أنواع",
    lead: "علامة كورية واحدة. 6 تركيبات — تختاري النوع حسب احتياج بشرتك.",
    priceFrom: 2500,
    mosaic: [
      "assets/products/arencia-nad-booster/hero-product.png?v=1",
      "assets/products/arencia-txa-booster/hero-product.png?v=1",
      "assets/products/arencia-retinal-booster/hero-product.png?v=1",
      "assets/products/arencia-vitamin-c-booster/hero-product.png?v=1",
    ],
    groups: [
      {
        id: "brighten",
        title: "إشراق وتوحيد اللون",
        blurb: "للبهتان والبقع الداكنة",
        productIds: ["arencia-vitamin-c-booster", "arencia-txa-booster"],
      },
      {
        id: "renew",
        title: "تجديد وحيوية",
        blurb: "للبشرة الباهتة والحساسة",
        productIds: ["arencia-nad-booster", "arencia-pdrn-booster"],
      },
      {
        id: "firm",
        title: "شد ليلي",
        blurb: "لثبات المظهر وعلامات التعب",
        productIds: ["arencia-retinal-booster"],
      },
      {
        id: "exfoliate",
        title: "تقشير وتنعيم",
        blurb: "للملمس الخشن والاحتقان",
        productIds: ["arencia-eraser-glycolic"],
      },
    ],
  },

  MEDICUBE_LINE: {
    href: "medicube.html",
    name: "خط medicube Capsule Cream",
    badge: "medicube · 5 أنواع",
    lead: "علامة كورية واحدة. 5 كريمات كبسولات — تختاري النوع حسب احتياج بشرتك.",
    priceFrom: 2500,
    mosaic: [
      "assets/products/medicube-txa-niacinamide/hero-product.png?v=1",
      "assets/products/medicube-vita-c/hero-product.png?v=1",
      "assets/products/medicube-hyaluronic/hero-product.png?v=1",
      "assets/products/medicube-pdrn-collagen/hero-product.png?v=1",
    ],
    groups: [
      {
        id: "brighten",
        title: "إشراق وتوحيد اللون",
        blurb: "للبقع والبهتان",
        productIds: ["medicube-txa-niacinamide", "medicube-vita-c", "medicube-kojic-turmeric"],
      },
      {
        id: "hydrate",
        title: "ترطيب",
        blurb: "للجفاف ودعم الحاجز الجلدي",
        productIds: ["medicube-hyaluronic"],
      },
      {
        id: "renew",
        title: "تجديد وكولاجين",
        blurb: "للبشرة المتعبة وفقدان التماسك",
        productIds: ["medicube-pdrn-collagen"],
      },
    ],
  },

  ANUA_LINE: {
    href: "anua.html",
    name: "خط Anua",
    badge: "Anua · 2 أنواع",
    lead: "علامة كورية واحدة. كريم PDRN للترطيب، أو سيروم نياسيناميد + TXA للبقع.",
    priceFrom: 2500,
    mosaic: [
      "assets/products/anua-pdrn-hyaluron/hero-product.png?v=1",
      "assets/products/anua-niacinamide-txa/hero-product.png?v=1",
    ],
    groups: [
      {
        id: "hydrate",
        title: "ترطيب",
        blurb: "للجفاف وقلة النضارة",
        productIds: ["anua-pdrn-hyaluron"],
      },
      {
        id: "brighten",
        title: "توحيد اللون",
        blurb: "للبقع الداكنة وتفاوت اللون",
        productIds: ["anua-niacinamide-txa"],
      },
    ],
    fallback: [
      { id: "anua-pdrn-hyaluron", name: "كريم Anua PDRN والهيالورونيك", description: "PDRN + هيالورونيك — ترطيب يومي خفيف. 60 مل.", price: 2500, image: "assets/products/anua-pdrn-hyaluron/hero-product.png?v=1" },
      { id: "anua-niacinamide-txa", name: "سيروم Anua نياسيناميد 10% + TXA 4%", description: "نياسيناميد 10% + TXA 4% — يلطّف مظهر البقع. 30 مل.", price: 2500, image: "assets/products/anua-niacinamide-txa/hero-product.png?v=1" },
    ],
  },

  ALTHEA_LINE: {
    href: "althea.html",
    name: "خط Dr. Althea 345",
    badge: "Dr. Althea · 2 أنواع",
    lead: "علامة كورية واحدة. رذاذ كريمي للترطيب، أو كريم تهدئة لآثار البثور.",
    priceFrom: 2500,
    mosaic: [
      "assets/products/althea-345-mist/hero-product.png?v=1",
      "assets/products/althea-345-cream/hero-product.png?v=1",
    ],
    groups: [
      {
        id: "mist",
        title: "رذاذ كريمي",
        blurb: "لترطيب سريع خلال اليوم",
        productIds: ["althea-345-mist"],
      },
      {
        id: "cream",
        title: "كريم تهدئة",
        blurb: "للبشرة الحساسة وآثار البثور",
        productIds: ["althea-345-cream"],
      },
    ],
    fallback: [
      { id: "althea-345-mist", name: "رذاذ Dr. Althea 345 الكريمي", description: "ماء نخالة الأرز + بانتينول — ترطيب خفيف. 60 مل.", price: 2500, image: "assets/products/althea-345-mist/hero-product.png?v=1" },
      { id: "althea-345-cream", name: "كريم Dr. Althea 345 للتهدئة", description: "نياسيناميد + بانتينول + سنتيلا — خالٍ من العطر. 50 مل.", price: 2500, image: "assets/products/althea-345-cream/hero-product.png?v=1" },
    ],
  },

  JOSEON_LINE: {
    href: "joseon.html",
    name: "خط Beauty of Joseon",
    badge: "Joseon · 3 أنواع",
    lead: "علامة كورية واحدة. واقيان شمس حسب نوع البشرة، وسيروم محيط العين ليلاً.",
    priceFrom: 2500,
    mosaic: [
      "assets/products/joseon-relief-sun/hero-product.png?v=1",
      "assets/products/joseon-aqua-fresh/hero-product.png?v=1",
      "assets/products/joseon-revive-eye/hero-product.png?v=1",
    ],
    groups: [
      {
        id: "sun",
        title: "حماية من الشمس",
        blurb: "واقيان حسب نوع البشرة",
        productIds: ["joseon-relief-sun", "joseon-aqua-fresh"],
      },
      {
        id: "eye",
        title: "محيط العين",
        blurb: "لعلامات التعب والخطوط الدقيقة",
        productIds: ["joseon-revive-eye"],
      },
    ],
    fallback: [
      { id: "joseon-relief-sun", name: "واقي شمس Joseon بالأرز والبروبيوتيك", description: "SPF50+ PA++++ — مرطّب للبشرة العادية والجافة. 50 مل.", price: 2500, image: "assets/products/joseon-relief-sun/hero-product.png?v=1" },
      { id: "joseon-aqua-fresh", name: "واقي شمس Joseon Aqua-fresh", description: "SPF50+ PA++++ — خفيف للبشرة المختلطة والدهنية. 50 مل.", price: 2500, image: "assets/products/joseon-aqua-fresh/hero-product.png?v=1" },
      { id: "joseon-revive-eye", name: "سيروم Joseon لمحيط العين", description: "جينسنغ + ريتينال — روتين ليلي. 30 مل.", price: 2500, image: "assets/products/joseon-revive-eye/hero-product.png?v=1" },
    ],
  },
};
